service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
     - httpApi:
        method: GET
        path: /products

  getProductById:
    handler: handlers/getProductById.getProductById
    events:
     - httpApi:
        method: GET
        path: /products/{productId}


  