service: product-service
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    REGION: ${self:provider.region}

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
     - httpApi:
        method: GET
        path: /products
    environment:
      ProductsTableName: ${env:PRODUCTS_TABLE}
      StockTableName: ${env:STOCK_TABLE}
  getProductById:
    handler: handlers/getProductById.getProductById
    events:
     - httpApi:
        method: GET
        path: /products/{productId}
    environment:
      ProductsTableName: ${env:PRODUCTS_TABLE}
  createProduct:
    handler: handlers/createProduct.createProduct
    events:
     - httpApi:
        method: POST
        path: /products
    environment:
      ProductsTableName: ${env:PRODUCTS_TABLE}

  