service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
     - http:
        path: products
        method: get
        cors: true
  getProductById:
    handler: handlers/getProductById.getProductById
    events:
     - http:
        path: products/{productId}
        method: get
        request:
          parameters:
            paths:
              productId: true

  