service: import-service
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    REGION: ${self:provider.region}
    BUCKET_NAME: ${env:BUCKET_NAME}
    QUEUE_NAME: ${env:QUEUE_NAME}
    SQS_URL: ${env:SQS_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:ListBucket"
          Resource: "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}"
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
        - Effect: Allow
          Action: "sqs:*"
          Resource: "arn:aws:sqs:eu-west-1:425140362966:${self:provider.environment.QUEUE_NAME}"

functions:
  importProductsFile:
    handler: src/handlers/importProductsFile.importProductsFile
    events:
      - httpApi:
          method: GET
          path: /import
  importFileParser:
    handler: src/handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
            - suffix: .csv
          existing: true
